"""Milestone 1 durable custody: opaque SQLite metadata plus encrypted objects.

All content-bearing state lives under one operator-selected runtime
directory outside Git, exactly as required by the Phase 3B Lifecycle and
Recovery Specification. This module never receives a filename, upload path,
or any other caller-controlled filesystem location for an admitted document;
callers only ever supply generated bytes and opaque identifiers. Encrypted
objects are written under an opaque object identity chosen by the caller
(never a supplied file name).

Backup, restore, external recovery-authority ledger attestation, and
passphrase/key rotation are explicitly out of Milestone 1 scope; this module
implements only local reconciliation (retain / hold-for-integrity-failure /
delete-orphan) as named in the Milestone 1 allowed capabilities.
"""

from __future__ import annotations

import os
import sqlite3
from datetime import datetime, timedelta, timezone
from pathlib import Path

from .crypto import (
    audit_event_hmac_hex,
    content_identity_for,
    decrypt_object,
    encrypt_object,
    EncryptedObject,
)
from .failures import CustodyFailure, DocumentAdmissionConflict
from .interfaces import CustodyReconciler, DurableObjectCustody
from .models import (
    AdmissionState,
    ContentIdentity,
    CustodyAuditEvent,
    CustodyObjectRecord,
    ReconciliationFinding,
    ReconciliationOutcome,
)
from .policies import CustodyPolicy, RetentionPolicy, synthetic_digest_policy

_OBJECT_KIND = "source"
_OBJECT_SUFFIX = ".enc"
_GENESIS_HMAC = "0" * 64


def _isoformat(value: datetime) -> str:
    if value.tzinfo is None:
        raise CustodyFailure("invalid_naive_datetime")
    return value.astimezone(timezone.utc).isoformat()


def _parse_iso(value: str) -> datetime:
    return datetime.fromisoformat(value)


class SqliteDurableRepository(DurableObjectCustody, CustodyReconciler):
    """SQLite metadata plus encrypted-object filesystem custody.

    ``runtime_directory`` is an operator-selected path outside Git. It is
    created if absent. The master key is supplied already-unlocked by the
    caller (see ``crypto.unwrap_master_key``); this class never derives or
    stores a passphrase.
    """

    def __init__(
        self,
        runtime_directory: Path,
        master_key: bytes,
        audit_key: bytes,
        custody_policy: CustodyPolicy,
    ) -> None:
        if not isinstance(runtime_directory, Path):
            raise CustodyFailure("invalid_runtime_directory")
        if not isinstance(master_key, bytes) or not master_key:
            raise CustodyFailure("invalid_master_key")
        if not isinstance(audit_key, bytes) or not audit_key:
            raise CustodyFailure("invalid_audit_key")
        self._runtime_directory = runtime_directory
        self._objects_directory = runtime_directory / "objects"
        self._objects_directory.mkdir(parents=True, exist_ok=True)
        self._master_key = master_key
        self._audit_key = audit_key
        self._custody_policy = custody_policy
        self._connection = sqlite3.connect(
            str(runtime_directory / "metadata.sqlite3")
        )
        self._connection.execute("PRAGMA foreign_keys = ON")
        self._initialize_schema()

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "SqliteDurableRepository":
        return self

    def __exit__(self, *_exc_info: object) -> None:
        self.close()

    def _initialize_schema(self) -> None:
        with self._connection:
            self._connection.execute(
                """
                CREATE TABLE IF NOT EXISTS receipts_reserved (
                    receipt_id TEXT PRIMARY KEY,
                    reserved_at TEXT NOT NULL
                )
                """
            )
            self._connection.execute(
                """
                CREATE TABLE IF NOT EXISTS objects (
                    object_id TEXT PRIMARY KEY,
                    admission_attempt_id TEXT NOT NULL,
                    receipt_id TEXT NOT NULL,
                    digest_policy_id TEXT NOT NULL,
                    digest_policy_version TEXT NOT NULL,
                    algorithm TEXT NOT NULL,
                    digest_hex TEXT NOT NULL,
                    byte_count INTEGER NOT NULL,
                    state TEXT NOT NULL,
                    encrypted_byte_count INTEGER NOT NULL,
                    header_version INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    retention_deadline TEXT NOT NULL,
                    legal_hold INTEGER NOT NULL,
                    tombstoned_at TEXT
                )
                """
            )
            self._connection.execute(
                """
                CREATE TABLE IF NOT EXISTS audit_events (
                    event_id TEXT PRIMARY KEY,
                    subject_id TEXT NOT NULL,
                    object_id TEXT,
                    event_kind TEXT NOT NULL,
                    reason_code TEXT NOT NULL,
                    recorded_at TEXT NOT NULL,
                    prior_event_hmac_hex TEXT NOT NULL,
                    event_hmac_hex TEXT NOT NULL
                )
                """
            )
            # Audit evidence is append-only for Milestone 1: no epoch pruning
            # transaction exists yet, so update/delete are always denied.
            self._connection.execute(
                """
                CREATE TRIGGER IF NOT EXISTS audit_events_no_update
                BEFORE UPDATE ON audit_events
                BEGIN
                    SELECT RAISE(ABORT, 'audit_events_are_append_only');
                END
                """
            )
            self._connection.execute(
                """
                CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
                BEFORE DELETE ON audit_events
                BEGIN
                    SELECT RAISE(ABORT, 'audit_events_are_append_only');
                END
                """
            )

    # -- receipt single-use reservation -----------------------------------

    def reserve_receipt(self, receipt_id: str, reserved_at: datetime) -> None:
        if not receipt_id:
            raise CustodyFailure("invalid_receipt_id")
        try:
            with self._connection:
                self._connection.execute(
                    "INSERT INTO receipts_reserved (receipt_id, reserved_at) "
                    "VALUES (?, ?)",
                    (receipt_id, _isoformat(reserved_at)),
                )
        except sqlite3.IntegrityError as error:
            raise DocumentAdmissionConflict(
                "receipt_already_used",
                receipt_id,
            ) from error

    # -- append-only audit chain -------------------------------------------

    def _last_event_hmac(self) -> str:
        row = self._connection.execute(
            "SELECT event_hmac_hex FROM audit_events "
            "ORDER BY rowid DESC LIMIT 1"
        ).fetchone()
        return row[0] if row is not None else _GENESIS_HMAC

    def append_audit_event(
        self,
        event_id: str,
        subject_id: str,
        object_id: str | None,
        event_kind: str,
        reason_code: str,
        recorded_at: datetime,
    ) -> CustodyAuditEvent:
        prior_hmac = self._last_event_hmac()
        canonical = "|".join(
            (
                event_id,
                subject_id,
                object_id or "",
                event_kind,
                reason_code,
                _isoformat(recorded_at),
                prior_hmac,
            )
        ).encode("utf-8")
        event_hmac = audit_event_hmac_hex(self._audit_key, canonical)
        event = CustodyAuditEvent(
            event_id=event_id,
            subject_id=subject_id,
            object_id=object_id,
            event_kind=event_kind,
            reason_code=reason_code,
            recorded_at=recorded_at,
            prior_event_hmac_hex=prior_hmac,
            event_hmac_hex=event_hmac,
        )
        with self._connection:
            self._connection.execute(
                "INSERT INTO audit_events ("
                "event_id, subject_id, object_id, event_kind, reason_code, "
                "recorded_at, prior_event_hmac_hex, event_hmac_hex"
                ") VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    event.event_id,
                    event.subject_id,
                    event.object_id,
                    event.event_kind,
                    event.reason_code,
                    _isoformat(event.recorded_at),
                    event.prior_event_hmac_hex,
                    event.event_hmac_hex,
                ),
            )
        return event

    def audit_history(self, subject_id: str) -> tuple[CustodyAuditEvent, ...]:
        rows = self._connection.execute(
            "SELECT event_id, subject_id, object_id, event_kind, reason_code, "
            "recorded_at, prior_event_hmac_hex, event_hmac_hex "
            "FROM audit_events WHERE subject_id = ? ORDER BY rowid ASC",
            (subject_id,),
        ).fetchall()
        return tuple(
            CustodyAuditEvent(
                event_id=row[0],
                subject_id=row[1],
                object_id=row[2],
                event_kind=row[3],
                reason_code=row[4],
                recorded_at=_parse_iso(row[5]),
                prior_event_hmac_hex=row[6],
                event_hmac_hex=row[7],
            )
            for row in rows
        )

    # -- object custody -----------------------------------------------------

    def _object_path(self, object_id: str) -> Path:
        return self._objects_directory / f"{object_id}{_OBJECT_SUFFIX}"

    def _write_object_atomically(self, object_id: str, raw: bytes) -> None:
        final_path = self._object_path(object_id)
        temporary_path = self._objects_directory / f".{object_id}.tmp"
        with temporary_path.open("wb") as handle:
            handle.write(raw)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, final_path)
        if os.name != "nt":
            directory_descriptor = os.open(
                str(self._objects_directory),
                os.O_RDONLY,
            )
            try:
                os.fsync(directory_descriptor)
            finally:
                os.close(directory_descriptor)

    def store(
        self,
        object_id: str,
        admission_attempt_id: str,
        receipt_id: str,
        plaintext: bytes,
        policy: CustodyPolicy,
        retention: RetentionPolicy,
        created_at: datetime,
    ) -> CustodyObjectRecord:
        if not object_id or not admission_attempt_id or not receipt_id:
            raise CustodyFailure("invalid_custody_identifiers")
        digest_policy = synthetic_digest_policy()
        identity: ContentIdentity = content_identity_for(
            plaintext,
            digest_policy.policy_id,
            digest_policy.policy_version,
        )
        encrypted: EncryptedObject = encrypt_object(
            plaintext,
            self._master_key,
            _OBJECT_KIND,
            object_id,
            policy,
        )
        raw = encrypted.to_bytes()
        try:
            self._write_object_atomically(object_id, raw)
        except OSError as error:
            raise CustodyFailure("object_write_failed", object_id) from error

        retention_deadline = created_at + timedelta(
            seconds=retention.temporary_retention_seconds
        )
        record = CustodyObjectRecord(
            object_id=object_id,
            admission_attempt_id=admission_attempt_id,
            receipt_id=receipt_id,
            content_identity=identity,
            state=AdmissionState.QUARANTINED,
            encrypted_byte_count=len(raw),
            header_version=policy.header_version,
            created_at=created_at,
            retention_deadline=retention_deadline,
            legal_hold=False,
            tombstoned_at=None,
        )
        try:
            with self._connection:
                self._connection.execute(
                    "INSERT INTO objects ("
                    "object_id, admission_attempt_id, receipt_id, "
                    "digest_policy_id, digest_policy_version, algorithm, "
                    "digest_hex, byte_count, state, encrypted_byte_count, "
                    "header_version, created_at, retention_deadline, "
                    "legal_hold, tombstoned_at"
                    ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        record.object_id,
                        record.admission_attempt_id,
                        record.receipt_id,
                        identity.digest_policy_id,
                        identity.digest_policy_version,
                        identity.algorithm,
                        identity.digest_hex,
                        identity.byte_count,
                        record.state.value,
                        record.encrypted_byte_count,
                        record.header_version,
                        _isoformat(record.created_at),
                        _isoformat(record.retention_deadline),
                        int(record.legal_hold),
                        None,
                    ),
                )
        except sqlite3.IntegrityError as error:
            raise DocumentAdmissionConflict(
                "object_id_already_used",
                object_id,
            ) from error
        self.append_audit_event(
            event_id=f"audit-{object_id}-quarantined",
            subject_id=admission_attempt_id,
            object_id=object_id,
            event_kind="custody_object_durable",
            reason_code="encrypted_object_durable",
            recorded_at=created_at,
        )
        return record

    def _row_to_record(self, row: tuple) -> CustodyObjectRecord:
        identity = ContentIdentity(
            digest_policy_id=row[3],
            digest_policy_version=row[4],
            algorithm=row[5],
            digest_hex=row[6],
            byte_count=row[7],
        )
        return CustodyObjectRecord(
            object_id=row[0],
            admission_attempt_id=row[1],
            receipt_id=row[2],
            content_identity=identity,
            state=AdmissionState(row[8]),
            encrypted_byte_count=row[9],
            header_version=row[10],
            created_at=_parse_iso(row[11]),
            retention_deadline=_parse_iso(row[12]),
            legal_hold=bool(row[13]),
            tombstoned_at=_parse_iso(row[14]) if row[14] else None,
        )

    def get(self, object_id: str) -> CustodyObjectRecord | None:
        row = self._connection.execute(
            "SELECT object_id, admission_attempt_id, receipt_id, "
            "digest_policy_id, digest_policy_version, algorithm, digest_hex, "
            "byte_count, state, encrypted_byte_count, header_version, "
            "created_at, retention_deadline, legal_hold, tombstoned_at "
            "FROM objects WHERE object_id = ?",
            (object_id,),
        ).fetchone()
        return self._row_to_record(row) if row is not None else None

    def list_active(self) -> tuple[CustodyObjectRecord, ...]:
        rows = self._connection.execute(
            "SELECT object_id, admission_attempt_id, receipt_id, "
            "digest_policy_id, digest_policy_version, algorithm, digest_hex, "
            "byte_count, state, encrypted_byte_count, header_version, "
            "created_at, retention_deadline, legal_hold, tombstoned_at "
            "FROM objects WHERE tombstoned_at IS NULL ORDER BY object_id"
        ).fetchall()
        return tuple(self._row_to_record(row) for row in rows)

    def retrieve_plaintext(self, object_id: str) -> bytes:
        record = self.get(object_id)
        if record is None or record.tombstoned_at is not None:
            raise CustodyFailure("object_not_available", object_id)
        path = self._object_path(object_id)
        if not path.exists():
            raise CustodyFailure("object_missing", object_id)
        raw = path.read_bytes()
        encrypted = EncryptedObject.from_bytes(raw)
        return decrypt_object(encrypted, self._master_key, _OBJECT_KIND, object_id)

    def tombstone(
        self,
        object_id: str,
        reason_code: str,
        tombstoned_at: datetime,
    ) -> CustodyObjectRecord:
        record = self.get(object_id)
        if record is None:
            raise CustodyFailure("object_not_found", object_id)
        if record.tombstoned_at is not None:
            return record
        path = self._object_path(object_id)
        if path.exists():
            path.unlink()
        with self._connection:
            self._connection.execute(
                "UPDATE objects SET tombstoned_at = ? WHERE object_id = ?",
                (_isoformat(tombstoned_at), object_id),
            )
        self.append_audit_event(
            event_id=f"audit-{object_id}-tombstoned-{tombstoned_at.timestamp()}",
            subject_id=record.admission_attempt_id,
            object_id=object_id,
            event_kind="custody_object_tombstoned",
            reason_code=reason_code,
            recorded_at=tombstoned_at,
        )
        return self.get(object_id)  # type: ignore[return-value]

    # -- reconciliation -------------------------------------------------

    def reconcile(
        self,
        checked_at: datetime,
    ) -> tuple[ReconciliationFinding, ...]:
        findings: list[ReconciliationFinding] = []
        finding_sequence = 0

        for record in self.list_active():
            path = self._object_path(record.object_id)
            if not path.exists():
                self._hold_for_integrity_failure(
                    record.object_id,
                    "missing_object",
                    checked_at,
                )
                finding_sequence += 1
                findings.append(
                    ReconciliationFinding(
                        finding_id=f"reconcile-{checked_at.timestamp()}-{finding_sequence}",
                        object_id=record.object_id,
                        outcome=ReconciliationOutcome.HELD_INTEGRITY_FAILURE,
                        reason_code="missing_object",
                        recorded_at=checked_at,
                    )
                )
                continue
            try:
                raw = path.read_bytes()
                encrypted = EncryptedObject.from_bytes(raw)
                decrypt_object(
                    encrypted,
                    self._master_key,
                    _OBJECT_KIND,
                    record.object_id,
                )
            except CustodyFailure:
                self._hold_for_integrity_failure(
                    record.object_id,
                    "invalid_object_authentication",
                    checked_at,
                )
                finding_sequence += 1
                findings.append(
                    ReconciliationFinding(
                        finding_id=f"reconcile-{checked_at.timestamp()}-{finding_sequence}",
                        object_id=record.object_id,
                        outcome=ReconciliationOutcome.HELD_INTEGRITY_FAILURE,
                        reason_code="invalid_object_authentication",
                        recorded_at=checked_at,
                    )
                )
                continue
            finding_sequence += 1
            findings.append(
                ReconciliationFinding(
                    finding_id=f"reconcile-{checked_at.timestamp()}-{finding_sequence}",
                    object_id=record.object_id,
                    outcome=ReconciliationOutcome.RETAINED,
                    reason_code="verified_committed_object",
                    recorded_at=checked_at,
                )
            )

        known_object_ids = {
            record.object_id for record in self.list_active()
        }
        for path in sorted(self._objects_directory.glob(f"*{_OBJECT_SUFFIX}")):
            object_id = path.name[: -len(_OBJECT_SUFFIX)]
            if object_id in known_object_ids:
                continue
            path.unlink()
            finding_sequence += 1
            findings.append(
                ReconciliationFinding(
                    finding_id=f"reconcile-{checked_at.timestamp()}-{finding_sequence}",
                    object_id=object_id,
                    outcome=ReconciliationOutcome.DELETED_ORPHAN,
                    reason_code="orphan_object_without_reserved_attempt",
                    recorded_at=checked_at,
                )
            )
            self.append_audit_event(
                event_id=f"audit-{object_id}-orphan-{checked_at.timestamp()}",
                subject_id=object_id,
                object_id=object_id,
                event_kind="custody_orphan_deleted",
                reason_code="orphan_object_without_reserved_attempt",
                recorded_at=checked_at,
            )

        return tuple(findings)

    def _hold_for_integrity_failure(
        self,
        object_id: str,
        reason_code: str,
        checked_at: datetime,
    ) -> None:
        with self._connection:
            self._connection.execute(
                "UPDATE objects SET state = ? WHERE object_id = ?",
                (AdmissionState.HELD.value, object_id),
            )
        self.append_audit_event(
            event_id=f"audit-{object_id}-held-{checked_at.timestamp()}",
            subject_id=object_id,
            object_id=object_id,
            event_kind="custody_integrity_failure",
            reason_code=reason_code,
            recorded_at=checked_at,
        )
