from .failures import (
    DocumentAdmissionValidationError,
    EvaluatorUnavailable,
    InspectionFailed,
    PolicyViolation,
    ResourceLimitExceeded,
)
from .interfaces import (
    ByteIntegrityVerifier,
    ConsumerEligibilityEvaluator,
    DocumentAdmissionOrchestrator,
    EvidenceJournal,
    FormatDetector,
    IsolatedInspector,
    PolicyEvaluator,
    QuarantineRepository,
    SecurityEvaluator,
)
from .models import (
    ADMISSION_TERMINAL_STATES,
    AdmissionAttemptRecord,
    AdmissionOperationContext,
    AdmissionState,
    AdmissionTransition,
    AuditEvent,
    CleanupEvidence,
    CleanupOperationContext,
    ConsumerEligibilityDecision,
    ConsumerEligibilityOutcome,
    EvaluationOutcome,
    ExtractionQuality,
    FormatDetectionResult,
    FormatDetectionState,
    InspectionOperationContext,
    InspectionResult,
    LegalHoldEvidence,
    PolicyEvaluation,
    QuarantineReceipt,
    RetryEvidence,
    RetryKind,
    SecurityEvaluation,
    SubmissionEnvelope,
    TransformationAttemptRecord,
    TransformationState,
    TransformationTransition,
)
from .policies import (
    AdmissionPolicies,
    InspectionPolicy,
    RetentionPolicy,
    SyntheticConsumerPolicy,
)
from .runtime import SyntheticPhase3BDocumentAdmissionRuntime


ACTOR_ID = "synthetic_document_admission_orchestrator"
COMPONENT_ID = "collector.document_admission"


class SyntheticDocumentAdmissionOrchestrator(
    DocumentAdmissionOrchestrator
):
    """Coordinates only generated bytes and injected synthetic evaluators."""

    def __init__(
        self,
        *,
        integrity_verifier: ByteIntegrityVerifier,
        quarantine: QuarantineRepository,
        journal: EvidenceJournal,
        detector: FormatDetector,
        security_evaluator: SecurityEvaluator,
        policy_evaluator: PolicyEvaluator,
        inspector: IsolatedInspector,
        eligibility_evaluator: ConsumerEligibilityEvaluator,
    ) -> None:
        dependencies = (
            (integrity_verifier, ByteIntegrityVerifier),
            (quarantine, QuarantineRepository),
            (journal, EvidenceJournal),
            (detector, FormatDetector),
            (security_evaluator, SecurityEvaluator),
            (policy_evaluator, PolicyEvaluator),
            (inspector, IsolatedInspector),
            (eligibility_evaluator, ConsumerEligibilityEvaluator),
        )
        if any(not isinstance(value, expected) for value, expected in dependencies):
            raise DocumentAdmissionValidationError(
                "invalid_orchestrator_dependency"
            )
        self._integrity_verifier = integrity_verifier
        self._quarantine = quarantine
        self._journal = journal
        self._detector = detector
        self._security_evaluator = security_evaluator
        self._policy_evaluator = policy_evaluator
        self._inspector = inspector
        self._eligibility_evaluator = eligibility_evaluator

    def submit(
        self,
        envelope: SubmissionEnvelope,
        payload: bytes,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
    ) -> AdmissionAttemptRecord:
        return self._submit(
            envelope=envelope,
            payload=payload,
            policies=policies,
            context=context,
            prior_attempt_id=None,
            retry=None,
        )

    def retry_admission(
        self,
        prior: AdmissionAttemptRecord,
        retry: RetryEvidence,
        envelope: SubmissionEnvelope,
        payload: bytes,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
    ) -> AdmissionAttemptRecord:
        if not isinstance(prior, AdmissionAttemptRecord):
            raise DocumentAdmissionValidationError(
                "invalid_prior_admission"
            )
        if prior.state not in ADMISSION_TERMINAL_STATES:
            raise DocumentAdmissionValidationError(
                "prior_admission_not_terminal"
            )
        if not isinstance(retry, RetryEvidence):
            raise DocumentAdmissionValidationError("invalid_retry_evidence")
        if not isinstance(context, AdmissionOperationContext):
            raise DocumentAdmissionValidationError(
                "invalid_admission_context"
            )
        if (
            context.admission_attempt_id
            == prior.admission_attempt_id
        ):
            raise DocumentAdmissionValidationError(
                "retry_requires_new_attempt_identity"
            )
        if retry.prior_attempt_id != prior.admission_attempt_id:
            raise DocumentAdmissionValidationError(
                "retry_prior_attempt_mismatch"
            )
        allowed = {
            AdmissionState.HELD: RetryKind.AUTHORIZED_REVIEW,
            AdmissionState.EVALUATION_FAILED: RetryKind.DEPENDENCY_RESTORED,
            AdmissionState.REJECTED: RetryKind.CORRECTED_RESUBMISSION,
        }
        if allowed.get(prior.state) is not retry.retry_kind:
            raise DocumentAdmissionValidationError("invalid_retry_kind")
        if prior.state is AdmissionState.REJECTED:
            if envelope.submission_id == prior.submission_id:
                raise DocumentAdmissionValidationError(
                    "corrected_resubmission_requires_new_submission"
                )
        elif envelope.submission_id != prior.submission_id:
            raise DocumentAdmissionValidationError(
                "retry_submission_mismatch"
            )
        return self._submit(
            envelope=envelope,
            payload=payload,
            policies=policies,
            context=context,
            prior_attempt_id=prior.admission_attempt_id,
            retry=retry,
        )

    def _submit(
        self,
        *,
        envelope: SubmissionEnvelope,
        payload: bytes,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
        prior_attempt_id: str | None,
        retry: RetryEvidence | None,
    ) -> AdmissionAttemptRecord:
        if not isinstance(envelope, SubmissionEnvelope):
            raise DocumentAdmissionValidationError("invalid_envelope")
        if not isinstance(payload, bytes):
            raise DocumentAdmissionValidationError("invalid_payload_type")
        if not isinstance(policies, AdmissionPolicies):
            raise DocumentAdmissionValidationError("invalid_policies")
        if not isinstance(context, AdmissionOperationContext):
            raise DocumentAdmissionValidationError(
                "invalid_admission_context"
            )
        policies.validate_envelope(envelope)
        if context.quarantined_at < envelope.received_at:
            raise DocumentAdmissionValidationError(
                "quarantined_before_received"
            )
        if len(payload) > policies.resources.max_input_bytes:
            raise ResourceLimitExceeded(
                "max_input_bytes_exceeded",
                envelope.submission_id,
            )

        identity = self._integrity_verifier.identify(
            payload,
            policies.digest,
        )
        receipt = self._quarantine.place(
            envelope,
            context.admission_attempt_id,
            context.quarantine_id,
            context.integrity_evidence_id,
            payload,
            identity,
            context.quarantined_at,
        )
        verification = self._quarantine.verify(
            receipt,
            context.integrity_verification_id,
            context.checked_at,
        )
        if not verification.matches:
            raise DocumentAdmissionValidationError(
                "quarantine_integrity_mismatch"
            )

        transitions: list[AdmissionTransition] = []
        self._record_admission_transition(
            transitions=transitions,
            transition_id=context.transition_ids[0],
            audit_event_id=context.audit_event_ids[0],
            envelope=envelope,
            attempt_id=context.admission_attempt_id,
            prior_state=AdmissionState.RECEIVED,
            next_state=AdmissionState.QUARANTINED,
            occurred_at=context.quarantined_at,
            reason_code="synthetic_quarantined",
            policy_id=policies.retention.policy_id,
            policy_version=policies.retention.policy_version,
            evidence_references=(receipt.integrity_evidence_id,),
        )
        self._record_admission_transition(
            transitions=transitions,
            transition_id=context.transition_ids[1],
            audit_event_id=context.audit_event_ids[1],
            envelope=envelope,
            attempt_id=context.admission_attempt_id,
            prior_state=AdmissionState.QUARANTINED,
            next_state=AdmissionState.VALIDATING,
            occurred_at=context.validating_at,
            reason_code="synthetic_validating",
            policy_id=policies.resources.policy_id,
            policy_version=policies.resources.policy_version,
            evidence_references=(verification.verification_id,),
        )

        isolated_payload = self._quarantine.open_for_evaluation(receipt)
        detection: FormatDetectionResult | None = None
        security: SecurityEvaluation | None = None
        policy: PolicyEvaluation | None = None
        terminal_state: AdmissionState
        reason_code: str
        try:
            detection = self._detector.detect(
                isolated_payload,
                envelope,
                context.admission_attempt_id,
                context.format_detection_id,
                policies.resources,
                context.checked_at,
            )
            self._validate_detection(detection, envelope, policies, context)
            terminal_state, reason_code = self._detection_disposition(
                detection
            )
            if terminal_state is AdmissionState.ACCEPTED:
                security = self._security_evaluator.evaluate(
                    isolated_payload,
                    envelope,
                    detection,
                    context.security_evaluation_id,
                    policies.resources,
                    context.checked_at,
                )
                self._validate_security(
                    security,
                    envelope,
                    policies,
                    context,
                )
                terminal_state, reason_code = self._evaluation_disposition(
                    security.outcome,
                    security.reason_code,
                )
            if terminal_state is AdmissionState.ACCEPTED:
                if security is None:
                    raise DocumentAdmissionValidationError(
                        "missing_security_evaluation"
                    )
                policy = self._policy_evaluator.evaluate(
                    envelope,
                    detection,
                    security,
                    context.policy_evaluation_id,
                    policies.consumer,
                    policies.retention,
                    policies.resources,
                    context.checked_at,
                )
                self._validate_policy(
                    policy,
                    envelope,
                    policies,
                    context,
                )
                terminal_state, reason_code = self._evaluation_disposition(
                    policy.outcome,
                    policy.reason_code,
                )
        except EvaluatorUnavailable as error:
            terminal_state = AdmissionState.EVALUATION_FAILED
            reason_code = error.reason_code
        except (PolicyViolation, ResourceLimitExceeded) as error:
            terminal_state = AdmissionState.REJECTED
            reason_code = error.reason_code

        self._record_admission_transition(
            transitions=transitions,
            transition_id=context.transition_ids[2],
            audit_event_id=context.audit_event_ids[2],
            envelope=envelope,
            attempt_id=context.admission_attempt_id,
            prior_state=AdmissionState.VALIDATING,
            next_state=terminal_state,
            occurred_at=context.completed_at,
            reason_code=reason_code,
            policy_id=policies.resources.policy_id,
            policy_version=policies.resources.policy_version,
            evidence_references=tuple(
                item
                for item in (
                    detection.detection_id if detection else None,
                    security.evaluation_id if security else None,
                    policy.evaluation_id if policy else None,
                )
                if item is not None
            ),
        )
        return AdmissionAttemptRecord(
            admission_attempt_id=context.admission_attempt_id,
            submission_id=envelope.submission_id,
            prior_admission_attempt_id=prior_attempt_id,
            retry_evidence=retry,
            state=terminal_state,
            quarantine_receipt=receipt,
            integrity_verification=verification,
            transitions=tuple(transitions),
            format_detection=detection,
            security_evaluation=security,
            policy_evaluation=policy,
            started_at=envelope.received_at,
            completed_at=context.completed_at,
            authorized_review_evidence_id=(
                retry.evidence_ids[0]
                if retry is not None
                and retry.retry_kind is RetryKind.AUTHORIZED_REVIEW
                else None
            ),
            disposition_reason_code=reason_code,
            correlation_id=envelope.correlation_id,
        )

    def inspect(
        self,
        admission: AdmissionAttemptRecord,
        policy: InspectionPolicy,
        consumer: SyntheticConsumerPolicy,
        context: InspectionOperationContext,
    ) -> TransformationAttemptRecord:
        return self._inspect(
            admission=admission,
            policy=policy,
            consumer=consumer,
            context=context,
            prior_attempt_id=None,
            retry=None,
        )

    def retry_inspection(
        self,
        admission: AdmissionAttemptRecord,
        prior: TransformationAttemptRecord,
        retry: RetryEvidence,
        policy: InspectionPolicy,
        consumer: SyntheticConsumerPolicy,
        context: InspectionOperationContext,
    ) -> TransformationAttemptRecord:
        if not isinstance(prior, TransformationAttemptRecord):
            raise DocumentAdmissionValidationError(
                "invalid_prior_transformation"
            )
        if prior.state is not TransformationState.PROCESSING_FAILED:
            raise DocumentAdmissionValidationError(
                "prior_transformation_not_failed"
            )
        if not isinstance(retry, RetryEvidence):
            raise DocumentAdmissionValidationError("invalid_retry_evidence")
        if not isinstance(context, InspectionOperationContext):
            raise DocumentAdmissionValidationError(
                "invalid_inspection_context"
            )
        if (
            context.transformation_attempt_id
            == prior.transformation_attempt_id
        ):
            raise DocumentAdmissionValidationError(
                "retry_requires_new_attempt_identity"
            )
        if retry.prior_attempt_id != prior.transformation_attempt_id:
            raise DocumentAdmissionValidationError(
                "retry_prior_attempt_mismatch"
            )
        if retry.retry_kind is RetryKind.CORRECTED_RESUBMISSION:
            raise DocumentAdmissionValidationError("invalid_retry_kind")
        return self._inspect(
            admission=admission,
            policy=policy,
            consumer=consumer,
            context=context,
            prior_attempt_id=prior.transformation_attempt_id,
            retry=retry,
        )

    def _inspect(
        self,
        *,
        admission: AdmissionAttemptRecord,
        policy: InspectionPolicy,
        consumer: SyntheticConsumerPolicy,
        context: InspectionOperationContext,
        prior_attempt_id: str | None,
        retry: RetryEvidence | None,
    ) -> TransformationAttemptRecord:
        if not isinstance(admission, AdmissionAttemptRecord):
            raise DocumentAdmissionValidationError("invalid_admission")
        if admission.state is not AdmissionState.ACCEPTED:
            raise DocumentAdmissionValidationError(
                "inspection_requires_accepted_admission"
            )
        if admission.quarantine_receipt is None:
            raise DocumentAdmissionValidationError(
                "missing_quarantine_receipt"
            )
        if not isinstance(policy, InspectionPolicy):
            raise DocumentAdmissionValidationError(
                "invalid_inspection_policy"
            )
        if not isinstance(consumer, SyntheticConsumerPolicy):
            raise DocumentAdmissionValidationError(
                "invalid_consumer_policy"
            )
        if not isinstance(context, InspectionOperationContext):
            raise DocumentAdmissionValidationError(
                "invalid_inspection_context"
            )
        if (
            admission.completed_at is None
            or context.started_at < admission.completed_at
        ):
            raise DocumentAdmissionValidationError(
                "inspection_before_admission_completion"
            )
        payload = self._quarantine.open_for_evaluation(
            admission.quarantine_receipt
        )
        result: InspectionResult | None = None
        decision: ConsumerEligibilityDecision | None = None
        state = TransformationState.PROCESSING_FAILED
        reason_code = "inspection_failed"
        try:
            result = self._inspector.inspect(
                payload,
                admission,
                context.transformation_attempt_id,
                context.inspection_result_id,
                policy,
                context.started_at,
                context.completed_at,
            )
            self._validate_inspection_result(
                result,
                admission,
                policy,
                context,
            )
            if (
                result.extraction_quality is ExtractionQuality.COMPLETE
                and not result.resource_observation.exceeded_limit_names
            ):
                decision = self._eligibility_evaluator.evaluate(
                    result,
                    consumer,
                    context.consumer_eligibility_decision_id,
                    context.decided_at,
                )
                self._validate_eligibility(decision, consumer, context)
                if (
                    decision.outcome
                    is ConsumerEligibilityOutcome.ELIGIBLE
                ):
                    state = TransformationState.READY
                    reason_code = decision.reason_code
                else:
                    reason_code = decision.reason_code
            elif result.extraction_quality is ExtractionQuality.PARTIAL:
                reason_code = "partial_output"
            elif result.resource_observation.exceeded_limit_names:
                reason_code = "resource_limit_reached"
            else:
                reason_code = result.failure_kind or "no_output"
        except (
            EvaluatorUnavailable,
            InspectionFailed,
            ResourceLimitExceeded,
        ) as error:
            reason_code = error.reason_code

        transition = TransformationTransition(
            transition_id=context.transition_id,
            submission_id=admission.submission_id,
            transformation_attempt_id=context.transformation_attempt_id,
            prior_state=TransformationState.PROCESSING,
            next_state=state,
            occurred_at=context.completed_at,
            actor_id=ACTOR_ID,
            component_id=COMPONENT_ID,
            reason_code=reason_code,
            policy_id=policy.policy_id,
            policy_version=policy.policy_version,
            correlation_id=admission.correlation_id,
        )
        self._journal.append_transformation_transition(transition)
        self._journal.append_audit_event(
            AuditEvent(
                event_id=context.audit_event_id,
                correlation_id=admission.correlation_id,
                subject_id=admission.submission_id,
                admission_attempt_id=admission.admission_attempt_id,
                transformation_attempt_id=context.transformation_attempt_id,
                event_kind="transformation_transition",
                actor_id=ACTOR_ID,
                component_id=COMPONENT_ID,
                reason_code=reason_code,
                policy_id=policy.policy_id,
                policy_version=policy.policy_version,
                recorded_at=context.completed_at,
                safe_evidence_references=tuple(
                    value
                    for value in (
                        result.inspection_result_id if result else None,
                        decision.decision_id if decision else None,
                    )
                    if value is not None
                ),
            )
        )
        return TransformationAttemptRecord(
            transformation_attempt_id=context.transformation_attempt_id,
            submission_id=admission.submission_id,
            admission_attempt_id=admission.admission_attempt_id,
            prior_transformation_attempt_id=prior_attempt_id,
            retry_evidence=retry,
            state=state,
            transitions=(transition,),
            inspection_result=result,
            consumer_eligibility_decision=decision,
            started_at=context.started_at,
            completed_at=context.completed_at,
            disposition_reason_code=reason_code,
            correlation_id=admission.correlation_id,
        )

    def cleanup(
        self,
        receipt: QuarantineReceipt,
        policy: RetentionPolicy,
        legal_hold: LegalHoldEvidence | None,
        context: CleanupOperationContext,
    ) -> CleanupEvidence:
        evidence = self._quarantine.delete(
            receipt,
            policy,
            legal_hold,
            context,
        )
        self._journal.append_audit_event(
            AuditEvent(
                event_id=context.audit_event_id,
                correlation_id=context.cleanup_id,
                subject_id=receipt.quarantine_id,
                admission_attempt_id=receipt.admission_attempt_id,
                transformation_attempt_id=None,
                event_kind="cleanup",
                actor_id=ACTOR_ID,
                component_id=COMPONENT_ID,
                reason_code=evidence.reason_code,
                policy_id=policy.policy_id,
                policy_version=policy.policy_version,
                recorded_at=context.completed_at,
                safe_evidence_references=(evidence.cleanup_id,),
            )
        )
        return evidence

    def _record_admission_transition(
        self,
        *,
        transitions: list[AdmissionTransition],
        transition_id: str,
        audit_event_id: str,
        envelope: SubmissionEnvelope,
        attempt_id: str,
        prior_state: AdmissionState,
        next_state: AdmissionState,
        occurred_at,
        reason_code: str,
        policy_id: str,
        policy_version: str,
        evidence_references: tuple[str, ...],
    ) -> None:
        transition = AdmissionTransition(
            transition_id=transition_id,
            submission_id=envelope.submission_id,
            admission_attempt_id=attempt_id,
            prior_state=prior_state,
            next_state=next_state,
            occurred_at=occurred_at,
            actor_id=ACTOR_ID,
            component_id=COMPONENT_ID,
            reason_code=reason_code,
            policy_id=policy_id,
            policy_version=policy_version,
            correlation_id=envelope.correlation_id,
        )
        self._journal.append_admission_transition(transition)
        self._journal.append_audit_event(
            AuditEvent(
                event_id=audit_event_id,
                correlation_id=envelope.correlation_id,
                subject_id=envelope.submission_id,
                admission_attempt_id=attempt_id,
                transformation_attempt_id=None,
                event_kind="admission_transition",
                actor_id=ACTOR_ID,
                component_id=COMPONENT_ID,
                reason_code=reason_code,
                policy_id=policy_id,
                policy_version=policy_version,
                recorded_at=occurred_at,
                safe_evidence_references=evidence_references,
            )
        )
        transitions.append(transition)

    @staticmethod
    def _detection_disposition(
        detection: FormatDetectionResult,
    ) -> tuple[AdmissionState, str]:
        mapping = {
            FormatDetectionState.DETECTED: AdmissionState.ACCEPTED,
            FormatDetectionState.UNSUPPORTED: AdmissionState.REJECTED,
            FormatDetectionState.AMBIGUOUS: AdmissionState.HELD,
            FormatDetectionState.UNAVAILABLE: AdmissionState.EVALUATION_FAILED,
        }
        return mapping[detection.state], detection.reason_code

    @staticmethod
    def _evaluation_disposition(
        outcome: EvaluationOutcome,
        reason_code: str,
    ) -> tuple[AdmissionState, str]:
        mapping = {
            EvaluationOutcome.PASS: AdmissionState.ACCEPTED,
            EvaluationOutcome.REJECT: AdmissionState.REJECTED,
            EvaluationOutcome.HOLD: AdmissionState.HELD,
            EvaluationOutcome.UNAVAILABLE: AdmissionState.EVALUATION_FAILED,
        }
        return mapping[outcome], reason_code
    @staticmethod
    def _validate_detection(
        detection: FormatDetectionResult,
        envelope: SubmissionEnvelope,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
    ) -> None:
        if (
            not isinstance(detection, FormatDetectionResult)
            or detection.detection_id != context.format_detection_id
            or detection.submission_id != envelope.submission_id
            or detection.admission_attempt_id
            != context.admission_attempt_id
            or detection.resource_policy_id
            != policies.resources.policy_id
            or detection.resource_policy_version
            != policies.resources.policy_version
        ):
            raise DocumentAdmissionValidationError(
                "invalid_format_detection_result"
            )

    @staticmethod
    def _validate_security(
        evaluation: SecurityEvaluation,
        envelope: SubmissionEnvelope,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
    ) -> None:
        if (
            not isinstance(evaluation, SecurityEvaluation)
            or evaluation.evaluation_id
            != context.security_evaluation_id
            or evaluation.submission_id != envelope.submission_id
            or evaluation.admission_attempt_id
            != context.admission_attempt_id
            or evaluation.resource_policy_id
            != policies.resources.policy_id
            or evaluation.resource_policy_version
            != policies.resources.policy_version
        ):
            raise DocumentAdmissionValidationError(
                "invalid_security_evaluation"
            )

    @staticmethod
    def _validate_policy(
        evaluation: PolicyEvaluation,
        envelope: SubmissionEnvelope,
        policies: AdmissionPolicies,
        context: AdmissionOperationContext,
    ) -> None:
        if (
            not isinstance(evaluation, PolicyEvaluation)
            or evaluation.evaluation_id
            != context.policy_evaluation_id
            or evaluation.submission_id != envelope.submission_id
            or evaluation.admission_attempt_id
            != context.admission_attempt_id
            or evaluation.consumer_policy_id
            != policies.consumer.policy_id
            or evaluation.consumer_policy_version
            != policies.consumer.policy_version
            or evaluation.retention_policy_id
            != policies.retention.policy_id
            or evaluation.retention_policy_version
            != policies.retention.policy_version
            or evaluation.deletion_policy_id
            != policies.retention.deletion_policy_id
            or evaluation.deletion_policy_version
            != policies.retention.deletion_policy_version
            or evaluation.resource_policy_id
            != policies.resources.policy_id
            or evaluation.resource_policy_version
            != policies.resources.policy_version
        ):
            raise DocumentAdmissionValidationError(
                "invalid_policy_evaluation"
            )

    @staticmethod
    def _validate_inspection_result(
        result: InspectionResult,
        admission: AdmissionAttemptRecord,
        policy: InspectionPolicy,
        context: InspectionOperationContext,
    ) -> None:
        if (
            not isinstance(result, InspectionResult)
            or result.inspection_result_id != context.inspection_result_id
            or result.submission_id != admission.submission_id
            or result.transformation_attempt_id
            != context.transformation_attempt_id
            or admission.quarantine_receipt is None
            or result.input_content_identity
            != admission.quarantine_receipt.content_identity
            or result.policy_id != policy.policy_id
            or result.policy_version != policy.policy_version
            or result.inspector_id != policy.inspector_id
            or result.inspector_version != policy.inspector_version
            or result.configuration_id != policy.configuration_id
            or result.configuration_version
            != policy.configuration_version
            or result.code_identity != policy.code_identity
            or result.code_version != policy.code_version
            or result.detected_format not in policy.allowed_formats
        ):
            raise DocumentAdmissionValidationError(
                "invalid_inspection_result"
            )

    @staticmethod
    def _validate_eligibility(
        decision: ConsumerEligibilityDecision,
        consumer: SyntheticConsumerPolicy,
        context: InspectionOperationContext,
    ) -> None:
        if (
            not isinstance(decision, ConsumerEligibilityDecision)
            or decision.decision_id
            != context.consumer_eligibility_decision_id
            or decision.transformation_attempt_id
            != context.transformation_attempt_id
            or decision.consumer_id != consumer.consumer_id
            or decision.consumer_policy_id != consumer.policy_id
            or decision.consumer_policy_version
            != consumer.policy_version
            or decision.intended_use != consumer.intended_use
            or decision.classification != consumer.classification
        ):
            raise DocumentAdmissionValidationError(
                "invalid_consumer_eligibility_decision"
            )


def build_phase3b_runtime(
    root_dir: str,
    passphrase: str,
) -> SyntheticPhase3BDocumentAdmissionRuntime:
    """Create the bounded synthetic Phase 3B runtime service."""
    return SyntheticPhase3BDocumentAdmissionRuntime(root_dir, passphrase)
