"""Milestone 1 composition root: ``DocumentCustodyRuntime``.

Wires signed-receipt verification, minimal PDF admission validation,
encrypted durable custody, and lifecycle operations into one local,
loopback-only synthetic vertical slice. This runtime never accepts a
filesystem path, upload directory, or supplied file name for an admitted
document; every admission call receives only an in-memory byte stream
supplied by its caller, simulating a browser push over loopback. Isolated
scanner, native-text, and OCR workers; the Human Review Workspace; backup
and restore; and passphrase rotation remain later-milestone concerns and are
intentionally absent from this composition root.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from .authorization import Ed25519ReceiptVerifier
from .durable_repository import SqliteDurableRepository
from .failures import AuthorizationFailure, DocumentAdmissionValidationError
from .models import AuthorizationReceipt, CustodyObjectRecord, DocumentFormat
from .policies import AuthorizationPolicy, CustodyPolicy, RetentionPolicy

_PDF_MAGIC = b"%PDF-"
_PDF_EOF_MARKER = b"%%EOF"
_EOF_SEARCH_WINDOW = 2048
_ZIP_MAGIC = b"PK\x03\x04"


def validate_pdf_admission(payload: bytes, max_bytes: int) -> None:
    """Minimal structural PDF admission validation.

    This checks only the declared-format signature, an end-of-file marker,
    and a bounded size. It performs no parsing, object-graph inspection, or
    text extraction; a later milestone's isolated scanner and native/OCR
    workers own actual content inspection.
    """

    if not isinstance(payload, bytes) or not payload:
        raise DocumentAdmissionValidationError("empty_payload")
    if len(payload) > max_bytes:
        raise DocumentAdmissionValidationError(
            "payload_exceeds_admission_limit"
        )
    if not payload.startswith(_PDF_MAGIC):
        raise DocumentAdmissionValidationError("missing_pdf_signature")
    if _PDF_EOF_MARKER not in payload[-_EOF_SEARCH_WINDOW:]:
        raise DocumentAdmissionValidationError("missing_pdf_eof_marker")


def validate_docx_admission(payload: bytes, max_bytes: int) -> None:
    if not isinstance(payload, bytes) or not payload:
        raise DocumentAdmissionValidationError("empty_payload")
    if len(payload) > max_bytes:
        raise DocumentAdmissionValidationError("payload_exceeds_admission_limit")
    if not payload.startswith(_ZIP_MAGIC):
        raise DocumentAdmissionValidationError("missing_docx_zip_signature")
    if b"[Content_Types].xml" not in payload:
        raise DocumentAdmissionValidationError("missing_docx_content_types")


def validate_text_admission(payload: bytes, max_bytes: int) -> None:
    if not isinstance(payload, bytes) or not payload:
        raise DocumentAdmissionValidationError("empty_payload")
    if len(payload) > max_bytes:
        raise DocumentAdmissionValidationError("payload_exceeds_admission_limit")
    try:
        decoded = payload.decode("utf-8")
    except UnicodeDecodeError as error:
        raise DocumentAdmissionValidationError("invalid_utf8_text_payload") from error
    if not decoded.strip():
        raise DocumentAdmissionValidationError("empty_text_payload")


def validate_admission_payload(
    payload: bytes,
    max_bytes: int,
    document_format: DocumentFormat,
) -> None:
    if document_format is DocumentFormat.PDF:
        validate_pdf_admission(payload, max_bytes)
        return
    if document_format is DocumentFormat.DOCX:
        validate_docx_admission(payload, max_bytes)
        return
    if document_format in (DocumentFormat.TXT, DocumentFormat.MARKDOWN):
        validate_text_admission(payload, max_bytes)
        return
    raise DocumentAdmissionValidationError("unsupported_document_format")


@dataclass(frozen=True)
class AdmissionResult:
    admission_attempt_id: str
    receipt_id: str
    record: CustodyObjectRecord


class DocumentCustodyRuntime:
    """Composition root for Milestone 1 synthetic intake and custody.

    Every public method receives only generated bytes and opaque
    identifiers supplied by its caller; none accepts a filesystem path.
    """

    def __init__(
        self,
        repository: SqliteDurableRepository,
        receipt_verifier: Ed25519ReceiptVerifier,
        authorization_policy: AuthorizationPolicy,
        retention_policy: RetentionPolicy,
        custody_policy: CustodyPolicy,
        max_admission_bytes: int,
    ) -> None:
        if max_admission_bytes <= 0:
            raise DocumentAdmissionValidationError(
                "invalid_max_admission_bytes"
            )
        self._repository = repository
        self._receipt_verifier = receipt_verifier
        self._authorization_policy = authorization_policy
        self._retention_policy = retention_policy
        self._custody_policy = custody_policy
        self._max_admission_bytes = max_admission_bytes

    def admit(
        self,
        receipt: AuthorizationReceipt,
        payload: bytes,
        admission_attempt_id: str,
        object_id: str,
        now: datetime,
        document_format: DocumentFormat = DocumentFormat.PDF,
    ) -> AdmissionResult:
        """Admit one browser-pushed byte stream under one signed receipt.

        Order matches the required transaction ordering: the receipt is
        verified and reserved as single-use before the payload is
        validated or made durable, so a valid receipt cannot be replayed
        even if the pushed bytes are later rejected.
        """

        verification = self._receipt_verifier.verify(
            receipt,
            self._authorization_policy,
            f"verify-{admission_attempt_id}",
            now,
        )
        if not verification.verified:
            raise AuthorizationFailure(
                verification.reason_code or "receipt_verification_failed",
                receipt.receipt_id,
            )
        self._repository.reserve_receipt(receipt.receipt_id, now)

        validate_admission_payload(
            payload=payload,
            max_bytes=self._max_admission_bytes,
            document_format=document_format,
        )

        record = self._repository.store(
            object_id=object_id,
            admission_attempt_id=admission_attempt_id,
            receipt_id=receipt.receipt_id,
            plaintext=payload,
            policy=self._custody_policy,
            retention=self._retention_policy,
            created_at=now,
        )
        return AdmissionResult(
            admission_attempt_id=admission_attempt_id,
            receipt_id=receipt.receipt_id,
            record=record,
        )
