services:
  jebediah-interaction:
    build:
      context: ../..
      dockerfile: services/jebediah-interaction/Dockerfile

    container_name: jebediah-interaction

    ports:
      - "8001:8001"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      MEMORY_URL: "http://jebediah-memory:8000"
      OLLAMA_URL: "http://host.docker.internal:11434"
      GENERATION_MODEL: "qwen3:8b"
      INTERACTION_SERVICE_TOKEN: "1a935048072548f9c0c491392f2374ac4a692998ad82909981f3784358df071c"

    networks:
      - default
      - jebediah-memory-network

networks:
  jebediah-memory-network:
    external: true
